// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Click() {
  return window['go']['main']['Timer']['Click']();
}

export function ClickTimeDifference() {
  return window['go']['main']['Timer']['ClickTimeDifference']();
}

export function EndCountdown() {
  return window['go']['main']['Timer']['EndCountdown']();
}

export function EndTimestamp() {
  return window['go']['main']['Timer']['EndTimestamp']();
}

export function Reset() {
  return window['go']['main']['Timer']['Reset']();
}

export function StartTimestamp() {
  return window['go']['main']['Timer']['StartTimestamp']();
}
