// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Click():Promise<void>;

export function ClickTimeDifference():Promise<number>;

export function EndCountdown():Promise<void>;

export function EndTimestamp():Promise<number>;

export function Reset():Promise<void>;

export function StartTimestamp():Promise<number>;
